insert into product (product_id, product_name, product_description) values (1, 'Latlux', 'Vestibulum sed magna at nunc commodo placerat.');
insert into product (product_id, product_name, product_description) values (2, 'Aerified', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into product (product_id, product_name, product_description) values (3, 'Trippledex', 'Donec semper sapien a libero.');
insert into product (product_id, product_name, product_description) values (4, 'Namfix', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into product (product_id, product_name, product_description) values (5, 'Zathin', 'Suspendisse accumsan tortor quis turpis.');
insert into product (product_id, product_name, product_description) values (6, 'Tampflex', 'Integer ac leo.');
insert into product (product_id, product_name, product_description) values (7, 'Subin', 'Morbi non quam nec dui luctus rutrum.');
insert into product (product_id, product_name, product_description) values (8, 'Tres-Zap', 'Quisque porta volutpat erat.');
insert into product (product_id, product_name, product_description) values (9, 'Veribet', 'Aliquam erat volutpat.');
insert into product (product_id, product_name, product_description) values (10, 'Fix San', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into product (product_id, product_name, product_description) values (11, 'Latlux', 'Aliquam non mauris.');
insert into product (product_id, product_name, product_description) values (12, 'Opela', 'Mauris lacinia sapien quis libero.');
insert into product (product_id, product_name, product_description) values (13, 'Subin', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into product (product_id, product_name, product_description) values (14, 'Stringtough', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into product (product_id, product_name, product_description) values (15, 'Viva', 'Morbi porttitor lorem id ligula.');
insert into product (product_id, product_name, product_description) values (16, 'Fintone', 'Curabitur in libero ut massa volutpat convallis.');
insert into product (product_id, product_name, product_description) values (17, 'Toughjoyfax', 'Maecenas tincidunt lacus at velit.');
insert into product (product_id, product_name, product_description) values (18, 'Overhold', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into product (product_id, product_name, product_description) values (19, 'Bytecard', 'Nam nulla.');
insert into product (product_id, product_name, product_description) values (20, 'Span', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into product (product_id, product_name, product_description) values (21, 'Voltsillam', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into product (product_id, product_name, product_description) values (22, 'Prodder', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into product (product_id, product_name, product_description) values (23, 'Tresom', 'Pellentesque viverra pede ac diam.');
insert into product (product_id, product_name, product_description) values (24, 'Hatity', 'Nullam varius.');
insert into product (product_id, product_name, product_description) values (25, 'It', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into product (product_id, product_name, product_description) values (26, 'Zaam-Dox', 'In congue.');
insert into product (product_id, product_name, product_description) values (27, 'Regrant', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into product (product_id, product_name, product_description) values (28, 'Toughjoyfax', 'Morbi non lectus.');
insert into product (product_id, product_name, product_description) values (29, 'Sonair', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into product (product_id, product_name, product_description) values (30, 'Otcom', 'In blandit ultrices enim.');



insert into sell (store_id, product_id, product_quantity, product_price) values (1, 1, 1, 100);
insert into sell (store_id, product_id, product_quantity, product_price) values (2, 2, 2, 200);
insert into sell (store_id, product_id, product_quantity, product_price) values (3, 3, 3, 300);
insert into sell (store_id, product_id, product_quantity, product_price) values (4, 4, 4, 400);
insert into sell (store_id, product_id, product_quantity, product_price) values (5, 5, 5, 500);
insert into sell (store_id, product_id, product_quantity, product_price) values (6, 6, 1, 100);
insert into sell (store_id, product_id, product_quantity, product_price) values (7, 7, 2, 200);
insert into sell (store_id, product_id, product_quantity, product_price) values (8, 8, 3, 300);
insert into sell (store_id, product_id, product_quantity, product_price) values (9, 9, 4, 400);
insert into sell (store_id, product_id, product_quantity, product_price) values (10, 10, 5, 500);
insert into sell (store_id, product_id, product_quantity, product_price) values (11, 11, 1, 100);
insert into sell (store_id, product_id, product_quantity, product_price) values (12, 12, 2, 200);
insert into sell (store_id, product_id, product_quantity, product_price) values (13, 13, 3, 300);
insert into sell (store_id, product_id, product_quantity, product_price) values (14, 14, 4, 400);
insert into sell (store_id, product_id, product_quantity, product_price) values (15, 15, 5, 500);
insert into sell (store_id, product_id, product_quantity, product_price) values (16, 16, 1, 100);
insert into sell (store_id, product_id, product_quantity, product_price) values (17, 17, 2, 200);
insert into sell (store_id, product_id, product_quantity, product_price) values (18, 18, 3, 300);
insert into sell (store_id, product_id, product_quantity, product_price) values (19, 19, 4, 400);
insert into sell (store_id, product_id, product_quantity, product_price) values (20, 20, 5, 500);
insert into sell (store_id, product_id, product_quantity, product_price) values (21, 21, 1, 100);
insert into sell (store_id, product_id, product_quantity, product_price) values (22, 22, 2, 200);
insert into sell (store_id, product_id, product_quantity, product_price) values (23, 23, 3, 300);
insert into sell (store_id, product_id, product_quantity, product_price) values (24, 24, 4, 400);
insert into sell (store_id, product_id, product_quantity, product_price) values (25, 25, 5, 500);
insert into sell (store_id, product_id, product_quantity, product_price) values (10, 26, 1, 100);
insert into sell (store_id, product_id, product_quantity, product_price) values (11, 27, 2, 200);
insert into sell (store_id, product_id, product_quantity, product_price) values (12, 28, 3, 300);
insert into sell (store_id, product_id, product_quantity, product_price) values (13, 29, 4, 400);
insert into sell (store_id, product_id, product_quantity, product_price) values (14, 30, 5, 500);